Repository honeycombio/honeycomb-kubernetes-agent, pull requests merged in 2021-12, with the labels that each got.

#198 fix: container metadata missing
  handlers/handlers_test.go
  processors/kubernetes.go
Labels: type: bug, version: bump patch

#199 docs: update developing for new build
  DEVELOPMENT.md
  RELEASING.md
  examples/quickstart.yaml
Labels: version: no bump, type: documentation, merge at will

#201 Prepping v2.2.1
  CHANGELOG.md
  version.txt
Labels: type: maintenance, version: no bump

#205 maint: update releasing notes for ci workflow and helm chart update
  RELEASING.md
  examples/quickstart.yaml
Labels: type: maintenance, version: no bump, type: documentation
