Repository honeycombio/honeycomb-kubernetes-agent, pull requests merged in 2022-11, with the labels that each got.

#302 Put the k8s metadata processor first
  handlers/handlers.go
  handlers/handlers_test.go
Labels: type: bug, status: review needed, version: bump patch

#303 prepare 2.5.5 release
  CHANGELOG.md
  examples/quickstart.yaml
  version.txt
Labels: no-changelog

#304 Add support for building sample keys from integer fields
  processors/sample.go
  processors/sample_test.go
Labels: type: bug, version: bump patch

#306 Prepare v2.5.6 release
  CHANGELOG.md
  examples/quickstart.yaml
  version.txt
Labels: type: maintenance, version: bump patch

#308 Add MinEventsPerSec to config
  docs/configuration-reference.md
  processors/sample.go
Labels: type: enhancement, status: review needed, version: bump minor

#311 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#312 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump
