Repository honeycombio/honeycomb-kubernetes-agent, pull requests merged in 2022-04, with the labels that each got.

#241 Add exclude capability for certain logging paths
  config/config.go
  go.mod
  go.sum
  handlers/handlers_test.go
  k8sagent/watcher.go
  main.go
  podtailer/podtailer.go
  podtailer/podtailer_test.go
  tailer/tailer.go
  tailer/tailer_test.go
Labels: type: enhancement, version: bump minor

#247 Prepare v2.5.0 release
  CHANGELOG.md
  examples/quickstart.yaml
  version.txt
Labels: type: maintenance, version: bump minor

#240 Update go to 1.18
  .circleci/config.yml
  go.mod
  go.sum
Labels: type: maintenance, version: no bump
