Repository honeycombio/honeycomb-kubernetes-agent, pull requests merged in 2022-01, with the labels that each got.

#210 Update dependabot label
  .github/dependabot.yml
Labels: type: maintenance, version: no bump

#214 maint: fix test step in circle ci workflow
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#200 add node metadata to metrics events
  config/config.go
  main.go
  metrics/metadata.go
  metrics/metrics_test.go
  metrics/processor.go
  metrics/resource.go
  service/runnable.go
  service/service.go
  testdata/nodes.json
Labels: type: enhancement, version: bump minor

#206 fix: check for existence of optional CPU stats to prevent exceptions
  metrics/metrics_test.go
  metrics/processor.go
  metrics/resource.go
  testdata/stats-summary.json
Labels: type: bug, version: bump patch

#217 prepare 2.3.0 release
  CHANGELOG.md
  examples/quickstart.yaml
  version.txt
Labels: type: maintenance, version: bump minor

#218 fix nil pointer dereference in runnable.go with includeNodeLabels
  service/runnable.go
Labels: type: bug, version: bump patch

#219 Prepare v2.3.1
  CHANGELOG.md
  examples/quickstart.yaml
  version.txt
Labels: type: maintenance, version: no bump
